controller_joint_names: [left_ankle_lateral_joint,left_ankle_swing_joint,left_elbow_joint,left_hip_lateral_joint,left_hip_swing_joint,left_hip_twist_joint,left_knee_joint,left_shoulder_lateral_joint,left_shoulder_swing_joint,right_ankle_lateral_joint,right_ankle_swing_joint,right_elbow_joint,right_hip_lateral_joint,right_hip_swing_joint,right_hip_twist_joint,right_knee_joint,right_shoulder_lateral_joint,right_shoulder_swing_joint, head_pan_joint, head_tilt_joint]







    
