<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bioloid">

    <!-- Pi is now predefined -->
    <!-- <xacro:property name="pi" value="3.14159"/> -->
    <xacro:property name="cad_dir" value="file:///$(find bioloid_master)/assets/cad"/>
    <xacro:property name="hip_offset_xy" value="0.0065"/>
    <xacro:property name="hip_offset_yx" value="0.0015"/>
    <xacro:property name="hip_offset_rot" value="0.7416"/>
    <!-- Typically, STL/DAE model units are in mm, but RViz units are in m, hence models must be scaled down by 1000. -->
    <xacro:macro name="default_geometry" params="cad_file suffix:=_FCD-Conv_BDR-Col extension:=dae">
        <geometry>
            <mesh filename="${cad_dir}/${cad_file}${suffix}.${extension}" scale="0.001 0.001 0.001"/>
        </geometry>
    </xacro:macro>
    <xacro:macro name="z_rot">
        <axis xyz="0 0 1"/>
    </xacro:macro>

    <!-- Select one and only one of the following include files -->
    <!-- 1) Standard parts of Bioloid Comprehensive humanoid with 18 AX-12+ servos, which have been replaced in custom version -->
    <!--    When using this URDF, ensure a transform from odom to base_link is being published -->
    <!-- <xacro:include filename="$(find bioloid_master)/urdf/bioloid_std_parts.xacro" ns="std_parts"/> -->
    <!-- 2) Custom parts of modified Bioloid Comprehensive humanoid, with CM-5 replaced by PC and custom sensors -->
    <!--    When using this URDF, ensure a transform from odom to imu_link is being published -->
    <xacro:include filename="$(find bioloid_master)/urdf/bioloid_custom_parts.xacro"/>

    <!-- Import gazebo_ros_control plugin -->
    <xacro:include filename="$(find bioloid_master)/urdf/bioloid_gazebo.xacro"/>

    <!-- <xacro:macro name="shoulder_swing_joint" params="prefix reflect x"> -->
    <xacro:macro name="shoulder_swing_joint" params="prefix reflect">
        <joint name="${prefix}_shoulder_swing_joint" type="revolute">
            <parent link="torso_link"/>
            <!-- <origin xyz="${reflect*(-0.032)} 0 0" rpy="0 ${reflect*(-pi/2)} ${x*pi}"/> -->
            <origin xyz="${reflect*(-0.032)} 0 0" rpy="${reflect*(-pi/2)} 0 ${reflect*(pi/2)}"/>
            <xacro:z_rot/>
            <child link="${prefix}_shoulder_swing_link"/>
            <limit lower="${-pi}" upper="${pi}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="shoulder_lateral_joint" params="prefix reflect">
        <joint name="${prefix}_shoulder_lateral_joint" type="revolute">
            <parent link="${prefix}_shoulder_swing_link"/>
            <!-- <origin xyz="${reflect*(-0.014)} 0 ${reflect*0.044}" rpy="${-pi/2} 0 0"/> -->
            <origin xyz="${reflect*(-0.014)} 0 ${reflect*0.044}" rpy="${-pi/2} ${pi/2} 0"/>
            <xacro:z_rot/>
            <child link="${prefix}_upper_arm_link"/>
            <limit lower="${-pi}" upper="${pi}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="elbow_joint" params="prefix reflect">
        <joint name="${prefix}_elbow_joint" type="revolute">
            <parent link="${prefix}_upper_arm_link"/>
            <origin xyz="${reflect*-0.0675} 0 0" rpy="0 0 0"/>
            <xacro:z_rot/>
            <child link="${prefix}_lower_arm_link"/>
            <limit lower="${-1.77}" upper="${1.77}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="hand_joint" params="prefix">
        <joint name="${prefix}_hand_joint" type="fixed">
            <parent link="${prefix}_lower_arm_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <child link="${prefix}_hand_link"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="hip_twist_joint" params="prefix reflect rotatex rotatez">
        <joint name="${prefix}_hip_twist_joint" type="revolute">
            <parent link="torso_link"/>
            <origin xyz="${reflect*(-0.033)-reflect*(hip_offset_xy)} ${hip_offset_yx-0.016} -0.0655" rpy="${rotatex*pi} 0 ${rotatez*pi}"/>
            <xacro:z_rot/>
            <child link="${prefix}_hip_twist_link"/>
            <limit lower="${-pi/4}" upper="${pi/4}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="hip_lateral_joint" params="prefix reflect">
        <joint name="${prefix}_hip_lateral_joint" type="revolute">
            <parent link="${prefix}_hip_twist_link"/>
            <origin xyz="0 ${-0.0153-hip_offset_yx*2} ${reflect*0.05}" rpy="${reflect*pi/2} 0 0"/>
            <xacro:z_rot/>
            <child link="${prefix}_hip_lateral_link"/>
            <limit lower="${-0.3}" upper="${1.0}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="hip_swing_joint" params="prefix reflect rotatex">
        <joint name="${prefix}_hip_swing_joint" type="revolute">
            <parent link="${prefix}_hip_lateral_link"/>
            <origin xyz="0 0 ${reflect*(-0.032)}" rpy="${rotatex*pi} ${-pi/2} 0"/>
            <xacro:z_rot/>
            <child link="${prefix}_upper_leg_link"/>
            <limit lower="${-pi/2}" upper="${1.9}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="knee_joint" params="prefix reflect">
        <joint name="${prefix}_knee_joint" type="revolute">
            <parent link="${prefix}_upper_leg_link"/>
            <origin xyz="${reflect*0.0145} ${reflect*0.075} 0" rpy="0 0 0"/>
            <xacro:z_rot/>
            <child link="${prefix}_lower_leg_link"/>
            <limit lower="${-pi}" upper="${0}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="ankle_swing_joint" params="prefix reflect">
        <joint name="${prefix}_ankle_swing_joint" type="revolute">
            <parent link="${prefix}_lower_leg_link"/>
            <origin xyz="${reflect*-0.0145} ${reflect*0.071} 0" rpy="0 0 0"/>
            <xacro:z_rot/>
            <child link="${prefix}_ankle_swing_link"/>
            <limit lower="${-0.45}" upper="${pi/2}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="ankle_lateral_joint" params="prefix reflect">
        <joint name="${prefix}_ankle_lateral_joint" type="revolute">
            <parent link="${prefix}_ankle_swing_link"/>
            <origin xyz="${reflect*0.032} 0 0" rpy="0 ${pi/2} 0"/>
            <xacro:z_rot/>
            <child link="${prefix}_ankle_lateral_link"/>
            <limit lower="${-0.7}" upper="${0.7}" effort="10" velocity="1.0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="foot_joint" params="prefix">
        <joint name="${prefix}_foot_joint" type="fixed">
            <parent link="${prefix}_ankle_lateral_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <child link="${prefix}_foot_link"/>
        </joint>
    </xacro:macro>

    <!-- Base -->
    <joint name="base_to_torso_joint" type="fixed">
        <parent link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
        <child link="torso_link"/>
    </joint>
    <link name="base_link">
    </link>

   <!-- Head -->

   <joint name="head_pan_joint" type="revolute">
    <origin rpy="0 0 -1.570795" xyz="0 0 0.03"/>
    <parent link="torso_link"/>
    <child link="head_pan_link"/>
    <axis xyz="0 0 1"/>
    <limit effort="30" velocity="1.0" lower="-1.45" upper="1.45" />
   </joint>
   <link name="head_pan_link">
    <origin xyz="0 0 0"/>
   </link>

   <joint name="head_tilt_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0.03227"/>
    <parent link="head_pan_link"/>
    <child link="head_tilt_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="30" velocity="1.0" lower="-0.3" upper="0.3" />
   </joint>
   <link name="head_tilt_link">
    <origin xyz="0 0 0"/>
  </link>

   <joint name="head_ee_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="head_tilt_link"/>
    <child link="head_ee_link"/>
   </joint>
   <link name="head_ee_link">
      <visual>
      <geometry>
        <mesh filename="package://bioloid_master/assets/cad/BIO-Head.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin rpy="1.5708 0 0.0" xyz="0 0 0"/>
    </visual>
    <origin xyz="0 0 0"/>
    
  </link>

    <!-- Torso to right shoulder -->
    <xacro:shoulder_swing_joint prefix="right" reflect="1"/>
    <link name="right_shoulder_swing_link">
        <visual>
            <xacro:default_geometry cad_file="FP04-F1"/>
            <origin xyz="-0.014 0 0.044" rpy="0 ${pi} ${-pi/2}"/>
        </visual>
        <collision name="right_shoulder_collision">
            <origin xyz="-0.006 0 0.0375"/>
            <geometry>
                <box size="0.039 0.052 0.036"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Torso to left shoulder -->
    <xacro:shoulder_swing_joint prefix="left" reflect="-1"/>
    <link name="left_shoulder_swing_link">
        <visual>
            <xacro:default_geometry cad_file="FP04-F1"/>
            <origin xyz="0.014 0 -0.044" rpy="0 0 ${pi/2}"/>
        </visual>
        <collision name="left_shoulder_collision">
            <origin xyz="0.006 0 -0.0375"/>
            <geometry>
                <box size="0.039 0.052 0.036"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right shoulder to upper arm -->
    <xacro:shoulder_lateral_joint prefix="right" reflect="1"/>
    <link name="right_upper_arm_link">
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="${pi} 0 ${pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-BU"/>
            <origin xyz="0 0 0.0185" rpy="${pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-WA"/>
            <origin xyz="0 0 0.019" rpy="${pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F3"/>
            <origin xyz="-0.0415 0 0" rpy="0 0 ${-pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F2"/>
            <origin xyz="-0.0675 0 0" rpy="0 ${pi/2} 0"/>
        </visual>
        <collision name="right_upper arm_collision_proximal">
            <origin xyz="-0.0148 0 0"/>
            <geometry>
                <box size="0.054 0.033 0.044"/>
            </geometry>
        </collision>
        <collision name="right_upper arm_collision_distal">
            <origin xyz="-0.0555 0 0"/>
            <geometry>
                <box size="0.047 0.033 0.052"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Left shoulder to upper arm -->
    <xacro:shoulder_lateral_joint prefix="left" reflect="-1"/>
    <link name="left_upper_arm_link">
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-BU"/>
            <origin xyz="0 0 -0.0185" rpy="${-pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-WA"/>
            <origin xyz="0 0 -0.019" rpy="${-pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F3"/>
            <origin xyz="0.0415 0 0" rpy="0 0 ${pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F2"/>
            <origin xyz="0.0675 0 0" rpy="0 ${-pi/2} 0"/>
        </visual>
        <collision name="left_upper arm_collision_proximal">
            <origin xyz="0.0148 0 0"/>
            <geometry>
                <box size="0.054 0.033 0.044"/>
            </geometry>
        </collision>
        <collision name="left_upper arm_collision_distal">
            <origin xyz="0.0555 0 0"/>
            <geometry>
                <box size="0.047 0.033 0.052"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right upper arm to lower arm -->
    <xacro:elbow_joint prefix="right" reflect="1"/>
    <link name="right_lower_arm_link">
        <!-- Motor 5 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="${pi} 0 ${pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-BU"/>
            <origin xyz="0 0 0.0185" rpy="${pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-WA"/>
            <origin xyz="0 0 0.019" rpy="${pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F3"/>
            <origin xyz="-0.0415 0 0" rpy="0 0 ${-pi/2}"/>
        </visual>
        <collision name="right_lower_arm_collision">
            <origin xyz="-0.0135 0 0"/>
            <geometry>
                <box size="0.051 0.033 0.044"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Left upper arm to lower arm -->
    <xacro:elbow_joint prefix="left" reflect="-1"/>
    <link name="left_lower_arm_link">
        <!-- Motor 6 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-BU"/>
            <origin xyz="0 0 -0.0185" rpy="${-pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-WA"/>
            <origin xyz="0 0 -0.019" rpy="${-pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F3"/>
            <origin xyz="0.0415 0 0" rpy="0 0 ${pi/2}"/>
        </visual>
        <collision name="left_lower_arm_collision">
            <origin xyz="0.017 0 0"/>
            <geometry>
                <box size="0.058 0.033 0.044"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right lower arm to hand -->
    <xacro:hand_joint prefix="right"/>
    <link name="right_hand_link">
        <visual>
            <xacro:default_geometry cad_file="FP04-F11"/>
            <origin xyz="-0.0415 0 0" rpy="${-pi} ${pi/2} 0"/>
        </visual>
        <collision name="right_palm_collision">
            <origin xyz="-0.039 0 0"/>
            <geometry>
                <box size="0.0131 0.0265 0.044"/>
            </geometry>
        </collision>
        <collision name="right_fingers_collision">
            <origin xyz="-0.0701 -0.0077 0"/>
            <geometry>
                <box size="0.0575 0.0175 0.035"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Left lower arm to hand -->
    <xacro:hand_joint prefix="left"/>
    <link name="left_hand_link">
        <visual>
            <xacro:default_geometry cad_file="FP04-F11"/>
            <origin xyz="0.0415 0 0" rpy="0 ${pi/2} 0"/>
        </visual>
        <collision name="left_palm_collision">
            <origin xyz="0.039 0 0"/>
            <geometry>
                <box size="0.0131 0.0265 0.044"/>
            </geometry>
        </collision>
        <collision name="left_fingers_collision">
            <origin xyz="0.0701 0.0077 0"/>
            <geometry>
                <box size="0.0575 0.0175 0.035"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Torso to right hip twist -->
    <xacro:hip_twist_joint prefix="right" reflect="1" rotatex="1" rotatez="0"/>
    <link name="right_hip_twist_link">
        <visual>
            <xacro:default_geometry cad_file="FP04-F5"/>
            <origin xyz="0 -${hip_offset_xy*2} 0.05" rpy="${pi} 0 0"/>
        </visual>
        <collision name="right_hip_twist_collision">
            <origin xyz="0 0.0008 0.041"/>
            <geometry>
                <box size="0.029 0.083 0.0405"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Torso to left hip twist -->
    <xacro:hip_twist_joint prefix="left" reflect="-1" rotatex="0" rotatez="1"/>
    <link name="left_hip_twist_link">
        <visual>
            <xacro:default_geometry cad_file="FP04-F5"/>
            <origin xyz="0 -${hip_offset_xy*2} -0.05" rpy="0 0 ${pi}"/>
        </visual>
        <collision name="left_hip_twist_collision">
            <origin xyz="0 0.0008 -0.041"/>
            <geometry>
                <box size="0.029 0.083 0.0405"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right hip twist to hip lateral -->
    <xacro:hip_lateral_joint prefix="right" reflect="1"/>
    <link name="right_hip_lateral_link">
        <!-- Motor 9 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F6"/>
            <origin xyz="-0.019 0.0145 0.016" rpy="0 ${-pi/2} ${-pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F6"/>
            <origin xyz="0.019 0.0145 0.016" rpy="0 ${-pi/2} ${pi/2}"/>
        </visual>
        <!-- Motor 11 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 -0.032" rpy="${pi} ${-pi/2} 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-BU"/>
            <origin xyz="0 0 -0.05" rpy="${-pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F7"/>
            <origin xyz="0 0.0145 -0.051" rpy="${pi/2} 0 ${-pi/2}"/>
        </visual>
        <collision name="right_hip_lateral_collision">
            <origin xyz="0 0.0135 -0.0153"/>
            <geometry>
                <box size="0.04 0.051 0.0721"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Left hip twist to hip lateral -->
    <xacro:hip_lateral_joint prefix="left" reflect="-1"/>
    <link name="left_hip_lateral_link">
        <!-- Motor 10 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="${pi} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F6"/>
            <origin xyz="-0.019 0.0145 -0.016" rpy="0 ${pi/2} ${-pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F6"/>
            <origin xyz="0.019 0.0145 -0.016" rpy="0 ${pi/2} ${pi/2}"/>
        </visual>
        <!-- Motor 12 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0.032" rpy="${pi} ${-pi/2} 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="BPF-BU"/>
            <origin xyz="0 0 0.05" rpy="${pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F7"/>
            <origin xyz="0 0.0145 0.051" rpy="${-pi/2} 0 ${-pi/2}"/>
        </visual>
        <collision name="left_hip_lateral_collision">
            <origin xyz="0 0.0135 0.0153"/>
            <geometry>
                <box size="0.04 0.051 0.0721"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right hip lateral to upper leg -->
    <xacro:hip_swing_joint prefix="right" reflect="1" rotatex="0"/>
    <link name="right_upper_leg_link">
        <visual>
            <xacro:default_geometry cad_file="FP04-F4"/>
            <origin xyz="0 0 0" rpy="${-pi/2} ${pi/2} 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F1"/>
            <origin xyz="0.0145 0.075 0" rpy="${pi/2} ${-pi/2} 0"/>
        </visual>
        <collision name="right_upper_leg_proximal_collision">
            <origin xyz="0 0.0214 0"/>
            <geometry>
                <box size="0.03 0.065 0.049"/>
            </geometry>
        </collision>
        <collision name="right_upper_leg_distal_collision">
            <origin xyz="0.0065 0.0675 0"/>
            <geometry>
                <box size="0.04 0.0371 0.049"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Left hip lateral to upper leg -->
    <xacro:hip_swing_joint prefix="left" reflect="-1" rotatex="1"/>
    <link name="left_upper_leg_link">
        <visual>
            <xacro:default_geometry cad_file="FP04-F4"/>
            <origin xyz="0 0 0" rpy="${pi/2} ${pi/2} 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F1"/>
            <origin xyz="-0.0145 -0.075 0" rpy="${-pi/2} ${-pi/2} 0"/>
        </visual>
        <collision name="left_upper_leg_proximal_collision">
            <origin xyz="0 -0.0214 0"/>
            <geometry>
                <box size="0.03 0.065 0.049"/>
            </geometry>
        </collision>
        <collision name="left_upper_leg_distal_collision">
            <origin xyz="-0.0065 -0.0675 0"/>
            <geometry>
                <box size="0.04 0.0371 0.049"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right upper leg to lower leg -->
    <xacro:knee_joint prefix="right" reflect="1"/>
    <link name="right_lower_leg_link">
        <!-- Motor 13 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="0 ${pi} ${-pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F3"/>
            <origin xyz="-0.0145 0.019 0" rpy="0 0 ${pi}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F4"/>
            <origin xyz="-0.0145 0.071 0" rpy="${pi/2} ${-pi/2} 0"/>
        </visual>
        <collision name="right_lower_leg_proximal_collision">
            <origin xyz="-0.0135 0 0"/>
            <geometry>
                <box size="0.051 0.033 0.044"/>
            </geometry>
        </collision>
        <collision name="right_lower_leg_distal_collision">
            <origin xyz="-0.0145 0.0492 0"/>
            <geometry>
                <box size="0.03 0.067 0.049"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Left upper leg to lower leg -->
    <xacro:knee_joint prefix="left" reflect="-1"/>
    <link name="left_lower_leg_link">
        <!-- Motor 14 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F3"/>
            <origin xyz="0.0145 -0.019 0" rpy="0 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F4"/>
            <origin xyz="0.0145 -0.071 0" rpy="${-pi/2} ${-pi/2} 0"/>
        </visual>
        <collision name="left_lower_leg_proximal_collision">
            <origin xyz="0.0135 0 0"/>
            <geometry>
                <box size="0.051 0.033 0.044"/>
            </geometry>
        </collision>
        <collision name="left_lower_leg_distal_collision">
            <origin xyz="0.0145 -0.0492 0"/>
            <geometry>
                <box size="0.03 0.067 0.049"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right lower leg to ankle swing -->
    <xacro:ankle_swing_joint prefix="right" reflect="1"/>
    <link name="right_ankle_swing_link">
        <!-- Motor 15 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="0 ${pi} 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F7"/>
            <origin xyz="-0.019 -0.0145 0" rpy="${pi} 0 ${pi/2}"/>
        </visual>
        <!-- Motor 17 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0.032 0 0" rpy="0 ${pi/2} 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F6"/>
            <origin xyz="0.048 -0.0145 0.019" rpy="${-pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F6"/>
            <origin xyz="0.048 -0.0145 -0.019" rpy="${pi/2} 0 0"/>
        </visual>
        <collision name="right_ankle_swing_collision">
            <origin xyz="0.0167 -0.0135 0"/>
            <geometry>
                <box size="0.0721 0.051 0.04"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Left lower leg to ankle swing -->
    <xacro:ankle_swing_joint prefix="left" reflect="-1"/>
    <link name="left_ankle_swing_link">
        <!-- Motor 16 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F7"/>
            <origin xyz="0.019 0.0145 0" rpy="${pi} 0 ${-pi/2}"/>
        </visual>
        <!-- Motor 18 -->
        <visual>
            <xacro:default_geometry cad_file="AX-12"/>
            <origin xyz="-0.032 0 0" rpy="${pi} ${pi/2} 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F6"/>
            <origin xyz="-0.048 0.0145 -0.019" rpy="${pi/2} 0 ${pi}"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F6"/>
            <origin xyz="-0.048 0.0145 0.019" rpy="${-pi/2} 0 ${pi}"/>
        </visual>
        <collision name="left_ankle_swing_collision">
            <origin xyz="-0.0167 0.0135 0"/>
            <geometry>
                <box size="0.0721 0.051 0.04"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right ankle swing to ankle lateral -->
    <xacro:ankle_lateral_joint prefix="right" reflect="1"/>
    <link name="right_ankle_lateral_link">
        <visual>
            <xacro:default_geometry cad_file="BPF-BU"/>
            <origin xyz="0 0 -0.05" rpy="${-pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F5"/>
            <origin xyz="0 0 -0.0153" rpy="${-pi/2} ${pi} 0"/>
        </visual>
        <collision name="right_ankle_lateral_collision">
            <origin xyz="0 0.009 -0.016"/>
            <geometry>
                <box size="0.029 0.0405 0.083"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Left ankle swing to ankle lateral -->
    <xacro:ankle_lateral_joint prefix="left" reflect="-1"/>
    <link name="left_ankle_lateral_link">
        <visual>
            <xacro:default_geometry cad_file="BPF-BU"/>
            <origin xyz="0 0 0.05" rpy="${pi/2} 0 0"/>
        </visual>
        <visual>
            <xacro:default_geometry cad_file="FP04-F5"/>
            <origin xyz="0 0 0.0153" rpy="${pi/2} ${pi} 0"/>
        </visual>
        <collision name="left_ankle_lateral_collision">
            <origin xyz="0 -0.009 0.016"/>
            <geometry>
                <box size="0.029 0.0405 0.083"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="1.0"/>
            <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001"/>
        </inertial>
    </link>

    <!-- Right ankle lateral to foot -->
    <xacro:foot_joint prefix="right"/>

    <!-- Left ankle lateral to foot -->
    <xacro:foot_joint prefix="left"/>

</robot>
